wowork_dir: ./work_dir/smarthome/xview1/ctrgcn_joint
model_saved_name: ./runs/smarthome_cv1_ctrgcn_joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /home/qilang/PythonProjects/ICME/smarthome/xview1/train_data_joint.npy
  label_path: /home/qilang/PythonProjects/ICME/smarthome/xview1/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /home/qilang/PythonProjects/ICME/smarthome/xview1/val_data_joint.npy
  label_path: /home/qilang/PythonProjects/ICME/smarthome/xview1/val_label.pkl

# model
model: model.ctrgcn.Model
model_args:
  num_class: 19
  num_point: 17
  num_person: 1
  in_channels: 2
  graph: graph.smarthome.Graph
  graph_args:
    layout: 'smarthome17'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [0,1]
batch_size: 8
test_batch_size: 8
num_epoch: 50
nesterov: True
