work_dir: ./work_dir/smarthome/xsub/ctrgcn_bone
model_saved_name: ./runs/smarthome_cs_ctrgcn_bone
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /home/qilang/PythonProjects/ICME/smarthome/xsub/train_data_bone.npy
  label_path: /home/qilang/PythonProjects/ICME/smarthome/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /home/qilang/PythonProjects/ICME/smarthome/xsub/val_data_bone.npy
  label_path: /home/qilang/PythonProjects/ICME/smarthome/xsub/val_label.pkl

# model
model: model.ctrgcn.Model

model_args:
  num_class: 31
  num_point: 17
  num_person: 2
  graph: graph.smarthome.Graph
  graph_args:
    layout: 'smarthome17'
    strategy: 'spatial'
#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [0,1]
batch_size: 8
test_batch_size: 8
num_epoch: 45
nesterov: True

